### ISSUE TITLE
The testcontainers test does not run

### ISSUE THREAD

**Issue by LorenzoBettini** [rafareyeslopez/spring-mysql-testcontainers-demo#2]
I think there are a few problems in the way the test using testcontainers is structured...

First of all, since it does not respect the default maven surefire patterns for tests, it is not automatically executed (see https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#includes)

If run directly from an IDE, e.g., Eclipse, the test fails because the init_mysql.sql cannot be found:

```
Caused by: org.testcontainers.ext.ScriptUtils$ScriptLoadException: Could not load classpath init script: init_mysql.sql. Resource not found.
	at org.testcontainers.ext.ScriptUtils.runInitScript(ScriptUtils.java:228)
```

In fact, that file should be in src/test/resources and not, as it is now, in src/test/main/resources.

Moving the contents of src/test/main/resources into src/test/resources the test fails because of

```
Caused by: java.lang.RuntimeException: Driver org.testcontainers.jdbc.ContainerDatabaseDriver claims to not accept jdbcUrl, jdbc:mysql://localhost:32787/rafa
	at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:108) ~[HikariCP-3.2.0.jar:na]
```

I guess this is due to some problems in the application.properties of src/test/main/resources (which wasn't previously read, but not it is, since I moved that into src/test/resources).

I'll try to provide a PR.

**Comment by rafareyeslopez** [comment]
Thanks for your contribution!
